name: semcentral
favicon: null
layout_spectrum: 0.9096638755872846
typography_spectrum: 0.45856
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d63f7'
    - '#9d938a'
    - '#391516'
    - '#d76c20'
    - '#feb830'
  brandStrength: 0.75
  lightness: 0.4340263595804572
  saturation: 0.9950128123164177
  rhythmicContrast: 0.9456171176861972
purpose: []
